# Generated by Django 3.1.2 on 2021-12-05 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211205_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='star',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
