# Generated by Django 3.1.2 on 2021-12-24 18:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(default=40.0550272),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(default=29.0848768),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLong', models.FloatField(default=40.0550272)),
                ('endLong', models.FloatField(default=40.0550272)),
                ('startLat', models.FloatField(default=40.0550272)),
                ('endLat', models.FloatField(default=40.0550272)),
                ('givenStar', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('travellerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
