# Generated by Django 3.1.2 on 2021-12-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211224_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
    ]
