# Generated by Django 3.1.2 on 2021-12-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_carpooling'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooling',
            name='start_time',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
