# Generated by Django 3.1.2 on 2022-01-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_carpooling_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registeredCarGroup',
            field=models.IntegerField(default=0),
        ),
    ]
