# Generated by Django 3.1.2 on 2022-01-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_registeredcargroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hes_code',
            field=models.CharField(default='PENDING', max_length=12),
        ),
    ]
