# Generated by Django 3.1.2 on 2022-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_hes_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hes_code',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING'), ('RISK', 'RISK')], default='PENDING', max_length=12),
        ),
    ]
