# Generated by Django 3.1.2 on 2022-01-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_carpooling_ppp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLong', models.FloatField(default=40.0550272)),
                ('endLong', models.FloatField(default=40.0550272)),
                ('startLat', models.FloatField(default=40.0550272)),
                ('endLat', models.FloatField(default=40.0550272)),
                ('shuttle_name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=1.5)),
                ('start_time', models.CharField(default='13:00', max_length=5)),
                ('remaining_capacity', models.PositiveIntegerField(default=20)),
                ('shuttle_plate', models.CharField(max_length=9)),
            ],
        ),
    ]
