# Generated by Django 3.1.2 on 2022-01-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_shuttle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='car_type',
            field=models.CharField(default='', max_length=15),
        ),
    ]
