# Generated by Django 3.1.2 on 2022-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220108_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='car_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
