# Generated by Django 3.1.2 on 2022-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_registeredshuttleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='car_type',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
